accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'logout.html'), name='logout'),

]

chara/urls.py
from django.urls import path
from . import views

app_name = 'chara'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('post/', views.CreateCharaView.as_view(), name='post'),
    path('edit/<int:pk>', views.EditView.as_view(), name='edit'),
    # path('comment/<int:pk>', views.CommentView.as_view(), name='comment'),
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
    path('charas/<int:category>', views.CategoryView.as_view(), name='charas_cat'),
    path('user-list/<int:user>', views.UserView.as_view(), name='user_list'),
    path('chara-detail/<int:pk>', views.DetailView.as_view(), name='chara_detail'),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('chara/<int:pk>/delete/', views.CharaDeleteView.as_view(), name='chara_delete'),
    path('chara/<int:pk>/chara_question/', views.CharaQuestionView.as_view(), name='chara_question'),
    path('chara_after/', views.CharaAfterView.as_view(), name='chara_after'),
]

charaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('chara.urls')),
    path('', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'password_reset_done.html'), name='password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
    )

chara/models.py
from django.db import models
from accounts.models import CustomUser
from django.urls import reverse

class  Category(models.Model):
    title = models.CharField(
        verbose_name='キャラ一覧',
        max_length=20)
    
    def __str__(self):
        return self.title

class CharaMake(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete = models.CASCADE
        )
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
        )
    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
        )
    comment = models.TextField(
        verbose_name='コメント',
        )
    image1 = models.ImageField(
        verbose_name='イメージ1',
        upload_to = 'charas',
        )
    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to='charas',
        blank=True,
        null=True
        )
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
        )
    
    def __str__(self):
        return self.title
    

chara/forms.py
from django import forms
from django.forms import ModelForm
from .models import CharaMake


class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = \
          'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'

        self.fields['email'].widget.attrs['placeholder'] = \
          'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'

        self.fields['title'].widget.attrs['placeholder'] = \
          'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'

        self.fields['message'].widget.attrs['placeholder'] = \
          'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'


class CharaMakeForm(ModelForm):
    class Meta:
        model = CharaMake
        fields = ['category', 'title', 'comment', 'image1', 'image2']



chara/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, ListView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CharaMakeForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import CharaMake
from django.views.generic import FormView
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage
from django.views.generic import DetailView, DeleteView, UpdateView



class IndexView(ListView):
    template_name = 'index.html'
    queryset = CharaMake.objects.order_by('posted_at')
    paginate_by = 9

@method_decorator(login_required, name='dispatch')
class CreateCharaView(CreateView):
    form_class = CharaMakeForm
    template_name = 'post_chara.html'
    success_url = reverse_lazy('chara:post_done')

    def form_valid(self,form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):    
    template_name = 'post_success.html'

class CategoryView(ListView):
    template_name ='index.html'
    paginate_by = 9
    def get_queryset(self):
        category_id = self.kwargs['category']
        categories = CharaMake.objects.filter(
          category=category_id).order_by('-posted_at')
        return categories
    
class UserView(ListView):
    template_name = 'index.html'
    paginate_by = 9
    def get_queryset(self):
        user_id = self.kwargs['user']
        user_list = CharaMake.objects.filter(
          user=user_id).order_by('-posted_at')
        return user_list
    
class DetailView(DetailView):
    template_name = 'detail.html'
    model = CharaMake

 

class MypageView(ListView):
    template_name = 'mypage.html'
    paginate_by = 9
    def get_queryset(self):
        queryset = CharaMake.objects.filter(
            user=self.request.user).order_by('-posted_at')
        return queryset

class CharaDeleteView(DeleteView):
    model = CharaMake
    template_name ='chara_delete.html'
    success_url = reverse_lazy('chara:chara_question')
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    

class CharaQuestionView(DeleteView):
    model = CharaMake
    template_name = 'chara_question.html'
    success_url = reverse_lazy('chara:chara_after')
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

class CharaAfterView(TemplateView):
    template_name = 'chara_after.html'

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('chara:contact')
    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = 'お問い合わせ: {}'.format(title)
        message = \
          '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:\n{3}'\
          .format(name, email, title, message)
        from_email = 'morelllusionfuhrer@gmail.com'
        to_list = ['morelllusionfuhrer@gmail.com']
        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list)
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)
    
@method_decorator(login_required, name='dispatch')
class EditView(UpdateView):
    template_name = 'hensyuu.html'
    model = CharaMake
    success_url = reverse_lazy('chara:post_done')
    fields = ['category', 'title', 'comment', 'image1', 'image2']
    def form_valid(self,form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

chara/templates/base.html
{% load static %}

<!doctype html>
<html lang="ja" data-bs-theme="auto">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{% block title %}{% endblock %}</title>

    <link rel="icon" href="favicon.ico">
    <link rel="icon" type="image/png" href="img/IMG_3401.JPG">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    

    

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      body {
        background-color: rgb(210, 247, 247);
      }

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      label {
        display: block;
      }
 
    </style>
  </head>

  <body>   
    <header data-bs-theme="dark">
      <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">キャラクターを作ろう</h4>
              <p class="text-muted">自分だけのキャラクターを忘れないように残そう!　　　
              もしかしたら推しができるかも?</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4>Contact</h4>
              <ul class="list-unstyled">
                {% if user.is_authenticated %}
                <li><a href="{% url 'chara:mypage' %}" class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}">ログアウト</a></li>
                <li><a href="{% url 'password_reset' %}" class="text-white">パスワードのリセット</a></li>
                <li><a href="{% url 'chara:contact' %}" class="text-white">お問い合わせ</a></li>
                {% else %}
                <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
                <li><a href="{% url 'chara:contact' %}" class="text-white">お問い合わせ</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <a href="{% url 'chara:index' %}" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <strong>Chara Memorys</strong>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main>
    {% block contents %}{% endblock %}
    </main>
    <footer class="text-body-secondary py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="{% url 'chara:index' %}">トップページに戻る</a>
        </p>
        
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

chara/templates/chara_after.html
{% extends 'base.html' %}
{% block title %}Chara After{% endblock %}

      {% block contents %}
      <br><br>
      <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4 style="color: rgb(0, 0, 219);">キャラとお別れしました...</h4>
                <h7 style="color: rgb(0, 0, 219);">忘れないでね</h7>
                <li><a href="{% url 'chara:mypage' %}" class="text-white">マイページに戻る</a></li>
            </div>
        </div>
    </div>
    {% endblock %}

chara/templates/chara_delete.html
{% extends 'base.html' %}
{% block title %}Chara Delete{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">

                    <br>
                    <p>この子とお別れしますか?</p>
                    {% csrf_token %}
                    <a href="{% url 'chara:chara_question' object.pk %}" class="btn btn-primary my-2">お別れする</a>
                    <!-- <button class="btn btn-primary my-2" type="submit">お別れする</button> -->
                    <a href="{% url 'chara:chara_detail' object.pk %}" class="btn btn-secondary my-2">やめる</a>
            </div>
        </div>
      </div>
      {% endblock %}

chara/templates/chara_question.html
{% extends 'base.html' %}
{% block title %}Chara Question{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">

                    <br>
                    <h3 style="color: rgb(216, 48, 48);">本当にこの子とお別れしますか?</h3>
                    {% csrf_token %}
                    <button class="btn btn-primary my-2" type="submit">お別れする</button>
                    <a href="{% url 'chara:chara_after' %}" class="btn btn-secondary my-2">やめる</a>
            </div>
        </div>
      </div>
      {% endblock %}

chara/templates/charas_list.html
  <div class="album py-5 bg-ligth">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ record.image1.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>
            <div class="card-body">
              <p class="card-text">
                {{record.title}}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"  onclick="location.href='{% url "chara:chara_detail" record.pk %}'">詳細</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary"  onclick="location.href='{% url "chara:charas_cat" category=record.category.id %}'">{{record.category.title}}</button>
                </div>
                <a href="{% url 'chara:user_list' user=record.user.id %}">
                  <small class="text-muted"> {{record.user.username}}</small>
                </a>
                <small class="text-muted">{{record.user.username}}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

chara/templates/charas_title.html
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light" href="{% url 'chara:index' %}">Chara Memorys</h1>
        <p class="lead text-muted">たくさんのキャラに出会おう!</p>
        <p>
          {% if user.is_authenticated %}
          <a href="{% url 'chara:post' %}" class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">ログインはここから!</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

chara/templates/comment.html
{% extends 'base.html' %}
{% block title %}Comment{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
            <div class="col offset-2">
              {% csrf_token %}
              <table>
                  <tr>
                      <th>ユーザー名</th>
                      <td>{{ form.title }}</td>
                  </tr>
                  <tr>
                      <th>コメント</th>
                      <td>{{ form.comment }}</td>
                  </tr>
              </table>
              <button type="submit">投稿する</button>
              </div>
            </div>
        </div>
      </div>
      {% endblock %}

chara/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contact{% endblock %}

      {% block contents %}
      <form action="" method="POST" class="text-center">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="送信" /><br>
      </form>
      {% endblock %}

chara/templates/detail.html
{% extends 'base.html' %}
{% block title %}Chara Detail{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
            <div class="col offset-3">
                <h2>{{object.title}}</h2>
                <p>{{object.comment}}</p>
                <br>
                <p>{{object.posted_at}}に投稿</p>
                <p><img src="{{ object.image1.url }}"></img></p>
                {% if object.image2 %}
                  <p><img src="{{ object.image2.url }}"></img></p>
                {% endif %}

                {% if request.user == object.user %}
                <form method="POST">
                <a href="{% url 'chara:chara_delete' object.pk %}" class="btn btn-primary my-2">お別れする</a>
                <a href="{% url 'chara:edit' object.pk %}" class="btn btn-primary my-2">編集する</a>
                
                {% endif %}

                
            </div>
        </div>
      </div>
      {% endblock %}

chara/templates/hensyuu.html
{% extends 'base.html' %}
{% block title %}Edit{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>種族</th>
                            <td>{{ form.category }}</td>
                        </tr>
                        <tr>
                            <th>キャラクター名</th>
                            <td>{{ form.title }}</td>
                        </tr>
                        <tr>
                            <th>キャラクターストーリー</th>
                            <td>{{ form.comment }}</td>
                        </tr>
                        <tr>
                            <th>イメージイラスト</th>
                            <td>{{ form.image1 }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">編集完了</button>
                </form>
            </div>
        </div>
      </div>
      {% endblock %}

chara/templates/index.html
{% extends 'base.html' %}

{% block title %}Chara Memorys{% endblock %}

      {% block contents %}
      {% include "charas_title.html" %}
      {% include "charas_list.html" %}
      {% include "pagenation.html" %}

      {% endblock %}

chara/templates/pagenation.html
<ul class="pagination" style="justify-content:center">
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}

        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}



    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li> 
    {% endif %}
</ul>

chara/templates/post_chara.html
{% extends 'base.html' %}
{% block title %}Post{% endblock %}

      {% block contents %}
      <br>
      <div class="container">
        <div class="row">
            <div class="col offset-2">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>種族</th>
                            <td>{{ form.category }}</td>
                        </tr>
                        <tr>
                            <th>キャラクター名</th>
                            <td>{{ form.title }}</td>
                        </tr>
                        <tr>
                            <th>キャラクターストーリー</th>
                            <td>{{ form.comment }}</td>
                        </tr>
                        <tr>
                            <th>イメージイラスト</th>
                            <td>{{ form.image1 }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </div>
        </div>
      </div>
      {% endblock %}

chara/templates/post_success.html
{% extends 'base.html' %}
{% block title %}Post Success{% endblock %}

      {% block contents %}
      <br><br>
      <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h4>投稿が完了しました!</h4>
                <h3>会いに行こう!</h3>
            </div>
        </div>
      </div>
      {% endblock %}